name: macos

on:
  workflow_dispatch:


jobs:
  greet:
    runs-on: macos-12
    steps:
      - name: Send greeting
        run: echo "Hello"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 查看文件
        run: |
          pwd
          ls -la
      - name: 安装go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.5' # The Go version to download (if necessary) and use.
          cache-dependency-path: go.sum
          go-version-file: 'go.mod'
      - name: 查看版本
        run: go version
      - name: 安装 wails 工具
        run: |
          cd wails/v3/cmd/wails
          go install
          wails
          cd ../../../..
      - name: 编译测试
        #      run: GOOS=darwin GOARCH=amd64 go build -gcflags=all="-N -l" -o main2 main.go
        run: |
          pwd
          wails task package:darwin
          ls -la
      - name: 查看编译的文件
        run: |
          ls -la
      - name: 保存 main2
        run: |
          mkdir -p /tmp/artifacts
          cp -r bin/qoq.app /tmp/artifacts/qoq.app
          chmod +x /tmp/artifacts/qoq.app/Contents/MacOS/qoq
      - name: 创建压缩包
        run: |
          cd /tmp/artifacts/
          zip -r ./qoq_MacOS.zip ./qoq.app
      - name: 上传产物
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: /tmp/artifacts/*.zip
